-- Homepage trust strip tags (e.g. Direct Factory Price).
create table if not exists public.hikuada_home_tags (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  label text not null,
  sort_order int not null default 100,
  is_active boolean not null default true
);

create index if not exists hikuada_home_tags_sort_idx on public.hikuada_home_tags (sort_order asc);

insert into public.hikuada_home_tags (label, sort_order, is_active)
select v.label, v.sort_order, v.is_active
from (
  values
    ('Direct Factory Price'::text, 10::int, true::boolean),
    ('Fast Shipping to Vietnam'::text, 20::int, true::boolean),
    ('Strict Quality Control'::text, 30::int, true::boolean)
) as v(label, sort_order, is_active)
where not exists (select 1 from public.hikuada_home_tags h where h.label = v.label);
