-- Homepage banner: multiple slides; carousel on site when more than one active slide.
-- Legacy singleton table hikuada_site_banner (if present) is migrated into the first slide once.

create table if not exists public.hikuada_banner_slides (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  image_url text not null,
  alt_text text,
  sort_order int not null default 100,
  is_active boolean not null default true
);

create index if not exists hikuada_banner_slides_active_sort_idx
  on public.hikuada_banner_slides (is_active, sort_order asc);

-- Migrate from old single-row banner table when it exists and slides are empty.
do $$
begin
  if to_regclass('public.hikuada_site_banner') is not null then
    insert into public.hikuada_banner_slides (image_url, alt_text, sort_order, is_active)
    select
      b.image_url,
      coalesce(
        nullif(trim(coalesce(b.alt_text, '')), ''),
        'Industrial frame manufacturing workshop'::text
      ),
      10,
      true
    from public.hikuada_site_banner b
    where b.id = 1
      and not exists (select 1 from public.hikuada_banner_slides limit 1);
  end if;
end $$;

insert into public.hikuada_banner_slides (image_url, alt_text, sort_order, is_active)
select
  '/banner-frame-gallery.png'::text,
  'Industrial frame manufacturing workshop'::text,
  10::int,
  true
where not exists (select 1 from public.hikuada_banner_slides limit 1);

-- Optional after verifying data: drop legacy table
-- drop table if exists public.hikuada_site_banner;
