create table if not exists public.hikuada_leads (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  customer_name text,
  whatsapp_zalo text,
  contact_type text,
  email text,
  country text,
  product_model text,
  message text
);

alter table public.hikuada_leads
  add column if not exists created_at timestamptz not null default now(),
  add column if not exists customer_name text,
  add column if not exists whatsapp_zalo text,
  add column if not exists contact_type text,
  add column if not exists email text,
  add column if not exists country text,
  add column if not exists product_model text,
  add column if not exists message text;
