create table if not exists public.hikuada_products (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  model text not null,
  category text not null default 'ps_moldings',
  sort_order integer not null default 100,
  size text not null,
  packing_spec text not null,
  stock_status text not null default 'In Stock',
  stock_quantity integer,
  image_url text
);

alter table public.hikuada_products
  add column if not exists created_at timestamptz not null default now(),
  add column if not exists model text,
  add column if not exists category text not null default 'ps_moldings',
  add column if not exists sort_order integer not null default 100,
  add column if not exists size text,
  add column if not exists packing_spec text,
  add column if not exists stock_status text not null default 'In Stock',
  add column if not exists stock_quantity integer,
  add column if not exists image_url text;
