create table if not exists public.hikuada_categories (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  slug text not null unique,
  name text not null,
  sort_order integer not null default 100,
  is_active boolean not null default true
);

alter table public.hikuada_categories
  add column if not exists created_at timestamptz not null default now(),
  add column if not exists slug text,
  add column if not exists name text,
  add column if not exists sort_order integer not null default 100,
  add column if not exists is_active boolean not null default true;

create unique index if not exists idx_hikuada_categories_slug on public.hikuada_categories (slug);
